---
development:
  cloud_name: hyo7tpkvo
  api_key: '325387769716627'
  api_secret: 2zWdcSdN5GjS5p-YhYvvgrF5dPs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hyo7tpkvo
  api_key: '325387769716627'
  api_secret: 2zWdcSdN5GjS5p-YhYvvgrF5dPs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hyo7tpkvo
  api_key: '325387769716627'
  api_secret: 2zWdcSdN5GjS5p-YhYvvgrF5dPs
  enhance_image_tag: true
  static_image_support: false
